export interface Registrant {
  id: string;
  nama: string;
  whatsapp: string;
  kategori: string;
  domisili: string;
  foto_url: string;
  jenis_kelamin: string;
  rank: number;
  points: number;
  seed: string;
  bio: string;
  prestasi: string;
  status?: string;
  alasan_status?: string | null;
  seeded_cup1?: boolean;
  seeded_participated?: boolean;
  seeded_player_name?: string | null;
  seeded_club_name?: string | null;
  seeded_division?: string | null;
  seeded_partners?: string[];
  seeded_source_no?: number | null;
  nama_panggilan?: string | null;
  nama_punggung?: string | null;
  tempat_lahir?: string | null;
  tanggal_lahir?: string | null;
  tahun_bergabung?: number | null;
  tangan_dominan?: string | null;
  hobi?: string | null;
  makanan_favorit?: string | null;
  pengalaman?: string | null;
}
